### ISSUE TITLE
Doesn’t account for multiple headings with the same text

### ISSUE THREAD

**Issue by delucis** [HiDeoo/starlight-links-validator#11]
### Describe the bug

Given a Markdown document with headings containing the same text, for example like this contrived one:

```md
## Heading

## Heading
```

`github-slugger` will auto-increment and attach an integer to the end of the generated `id`. So the above Markdown generates the following HTML:

```html
<h2 id="heading">Heading</h2>
<h2 id="heading-1">Heading</h2>
```

This tool [uses the stateless version of `github-slugger`](https://github.com/HiDeoo/starlight-links-validator/blob/f9c988bece239a17c38d1f1c64ffd0c98e15cd6e/packages/starlight-links-validator/libs/remark.ts#L38), so does not expect this behaviour and will fail for links to `#heading-1` in this case:

### To Reproduce

1. Create a document with headings containing the same text.
2. Link to one of the later headings (e.g. with a `-1` suffix).
3. Run the link validator.
4. It will error and flag the `-1` link.

### Expected behavior

Link anchor slugging logic should match the Astro project’s logic and the validation should pass.

### How often does this bug happen?

Every time

### System Info

Observed on macOS, but I suspect that’s not relevant.

**Comment by HiDeoo** [comment]
The fix has been published in [`v0.4.1`](https://github.com/HiDeoo/starlight-links-validator/releases/tag/v0.4.1).
