### ISSUE TITLE
Incorrect page paths on Windows

### ISSUE THREAD

**Issue by Genteure** [HiDeoo/starlight-links-validator#13]
### Describe the bug

When running on Windows, the generate page paths are missing `/`.

```
▶ guidesnamespacetest/
└─ /guides/namespacetest/#some-content
```

https://github.com/Genteure/starlight-links-validator/actions/runs/6763151427/job/18379935239#step:7:23

### To Reproduce

Run `astro build` in any project with `starlight-links-validator` on a Windows machine.

```diff
 jobs:
   lint_test:
     name: Lint & Test
-    runs-on: ubuntu-latest
+    strategy:
+      fail-fast: false
+      matrix:
+        os: [ubuntu-latest, windows-latest]
+    runs-on: ${{ matrix.os }}
```

### Expected behavior

starlight-links-validator should also work on Windows.

### How often does this bug happen?

Every time

**Comment by HiDeoo** [comment]
The fix has been published in [v0.4.2](https://github.com/HiDeoo/starlight-links-validator/releases/tag/v0.4.2).
