### ISSUE TITLE
Add rule to enforce use of same-locale links

### ISSUE THREAD

**Issue by delucis** [HiDeoo/starlight-links-validator#17]
### Is your feature request related to a problem?

In multilingual sites it’s easy to forget to update links when translating a page and leave a link to the original language instead of the translation language. These links are not strictly speaking “broken”, but they move the reader from their preferred language to a different language in a way that is unexpected and confusing.

### Describe the solution you'd like

A rule that catches relative links that are not to the current locale would be helpful.

For example, given these two Markdown files:

```md
---
# about.md
title: About
---

[Visit the home page](/)
```

```md
---
# fr/about.md
title: À propos
---

[Visiter l’accueil](/)
```

The first would be valid (assuming a default root locale), but the second link would be an error because it points to the default root locale and not the correct locale (`/fr/`).

### Describe alternatives you've considered

Manually searching through the codebase to find these mistakes.

### Additional Context

- May be best supported after [Starlight’s plugins API](https://github.com/withastro/starlight/discussions/962) is released as it would allow the link validator to easily access i18n config.

- Potentially out of scope for this tool, but hypothetically this kind of rule is a good candidate for “auto-fixing”. As it isn’t a standalone CLI that can be run with flags like `--fix` or `--dry-run` that may not be the easiest to use though.

**Comment by HiDeoo** [comment]
This is now supported in [`v0.5.0`](https://github.com/HiDeoo/starlight-links-validator/releases/tag/v0.5.0) release by setting the new [`errorOnInconsistentLocale`](https://starlight-links-validator.vercel.app/configuration/#erroroninconsistentlocale) option to `true`:

```js
export default defineConfig({
  integrations: [
    starlight({
      plugins: [
        starlightLinksValidator({
          errorOnInconsistentLocale: true,
        }),
      ],
    }),
  ],
})
```
