### ISSUE TITLE
Anchors inside the page are reported as faults

### ISSUE THREAD

**Issue by sansary** [HiDeoo/starlight-links-validator#18]
### Describe the bug

Any link of the form page#123
is reported as invalid while it is actually working

### To Reproduce

create a pageA containing a heading #x
create a pageB containing a reference to pageA#x
the validator will complain

### Expected behavior

create a pageA containing a heading #x
create a pageB containing a reference to pageA#x
the validator will complain

### How often does this bug happen?

Every time

### System Info

Macos 12.2.1

**Comment by HiDeoo** [comment]
Thanks for your feedback.

Relative file paths is not something I am planning to personally add support for. I personally think they are usually error prone and add an additional layer of complexity for the authors as you have to know where your current file is located and then calculate the relative path to the file you want to link to, which can become easily confusing with links like `../../some/other/file#thingy` vs just `/some/other/file#thingy`.

That being said, I'm not opposed to reviewing a PR that would add support for this (probably as an opt-in feature for the reasons mentioned above).
