### ISSUE TITLE
Verify relative links

### ISSUE THREAD

**Issue by tmcw** [HiDeoo/starlight-links-validator#19]
### Is your feature request related to a problem?

For a site with lots of content in nested folders, I was using relative links, like

```md
[HTTP](./http)
```

This isn't validated by this plugin - the internal link filter requires that links are absolute:

https://github.com/HiDeoo/starlight-links-validator/blob/72fab3d26513ee181afd04c3bf0c350440a5e725/packages/starlight-links-validator/libs/remark.ts#L133-L135

### Describe the solution you'd like

I'd like this to resolve relative links.

**Comment by HiDeoo** [comment]
Thanks for your feedback. I recently commented on a similar topic:

> Relative file paths is not something I am planning to personally add support for. I personally think they are usually error prone and add an additional layer of complexity for the authors as you have to know where your current file is located and then calculate the relative path to the file you want to link to, which can become easily confusing with links like ../../some/other/file#thingy vs just /some/other/file#thingy.

That being said, I'm not opposed at all to discuss or review a PR that would add support for this (probably as an opt-in feature for the reasons mentioned above).
