### ISSUE TITLE
Links are not validated correctly when `trailingSlash` is set to `never`

### ISSUE THREAD

**Issue by cantemizyurek** [HiDeoo/starlight-links-validator#20]
### Describe the bug

trailingSlash set to never it is not able to validate absolute paths regardless of you put trailing slash at the end.

### To Reproduce

export default defineConfig({
  integrations: [
    starlightLinksValidator(),
    starlight()
  ],
  trailingSlash: 'never'
})

### Expected behavior

to work.

### How often does this bug happen?

Every time

**Comment by HiDeoo** [comment]
Thanks for your report :raised_hands:

This should now be fixed in the new [`v0.5.0`](https://github.com/HiDeoo/starlight-links-validator/releases/tag/v0.5.0) release.
