### ISSUE TITLE
Ability to use outside of starlight

### ISSUE THREAD

**Issue by steveoh** [HiDeoo/starlight-links-validator#28]
### Is your feature request related to a problem?

https://github.com/withastro/roadmap/discussions/739

### Describe the solution you'd like

I would like internal link checking to be opt in with all astro websites and external links made available somehow so we could check their response codes.

### Describe alternatives you've considered

nothing available at the moment during build time.

### Additional Context

I have a discussion item open with astro but it has zero traction.

**Comment by HiDeoo** [comment]
Thanks for your feedback.

This validator is a Starlight plugin as it relies on the Starlight plugin API to get Starlight specific configuration informations to provide a better validation experience, specifically around the i18n features of Starlight. Such values are not available in contexts outside of the Starlight plugin API so some features will not be available if the validator was more generic.

I think a more generic validator for Astro (and no Starlight) could totally exists as an [Astro integration](https://docs.astro.build/en/reference/integrations-reference/), this does not have to be a part of Astro itself. It could even validate external links too like you mentioned (which is something I am not interested in doing in this validator).

**Comment by steveoh** [comment]
Would you mind sharing some of your knowledge on the subject and how it could be achieved as an integration in this discussion? https://github.com/withastro/roadmap/discussions/739

**Comment by HiDeoo** [comment]
Here are the few points I can think of that could help you to get started:

- You could take a look at the [version `0.4.2`](https://github.com/HiDeoo/starlight-links-validator/tree/v0.4.2) of this plugin which at the time was not a Starlight plugin but an integration and how it collected/validated internal links:
  - A custon remark plugin added in the [`astro:config:setup`](https://docs.astro.build/en/reference/integrations-reference/#astroconfigsetup) integration hook to collect all the internal links
  - A validation process call in the [`astro:build:done`](https://docs.astro.build/en/reference/integrations-reference/#astrobuilddone) integration hook to validate all the collected links
- You could also take a look at how it's done in Astro Docs (I have no idea personally how it's done there as I never looked at it but I'm sure it could be a good source of inspiration)
- Look at similar tool for other frameworks if such tools exist (I'm sure they do)
- Regarding the external links part, I personally have no idea as it's not something I took the time to look at, no sure what would be the best approach here considering some websites could be temporary down or something like that.
