### ISSUE TITLE
Plugin does not complain about links not ending with a slash when trailingSlash is set to always

### ISSUE THREAD

**Issue by sschultze** [HiDeoo/starlight-links-validator#33]
### Describe the bug

If `trailingSlash` is set to `always`, the plugin does not complain about links **not** ending with a trailing slash.

### To Reproduce

1. Set `trailingSlash` to `always`
2. Create a link without a trailing slash, e.g. `/en/pricing`

### Expected behavior

The plugin should complain about the link because it does not end with a slash.

### How often does this bug happen?

Every time

**Comment by HiDeoo** [comment]
Thanks for your report :raised_hands:

This should now be fixed in [`v0.7.0`](https://github.com/HiDeoo/starlight-links-validator/releases/tag/v0.7.0) that I just released.

**Comment by sschultze** [comment]
Wow, this was fast! 🚀 Thank you! ☺️
