### ISSUE TITLE
Add an ignore list, or a function that will be called on each url

### ISSUE THREAD

**Issue by stavros-k** [HiDeoo/starlight-links-validator#37]
### Is your feature request related to a problem?

We use a bunch of redirects with Cloudflare as some-short of a link shortener. eg `/s/discord` redirects to `https://discord...`
So a lot of our links in our md pages are `[Discord](/s/discord)`, That way we can change the URL without having to touch all the files. 
This makes validator error out.

### Describe the solution you'd like

Provide a way to "override" the result of the validation per url.
Either ignore list of a function that will be called per url.

### Describe alternatives you've considered

Creating "dumb" pages in `docs/` eg `docs/s/discord.md`

**Comment by HiDeoo** [comment]
Thanks for your feedback :raised_hands:

Interesting, this is not something I considered before. Small question as I am not familiar with: do Cloudflare redirects work locally?

**Comment by stavros-k** [comment]
> Thanks for your feedback :raised_hands:
> 
> 
> 
> Interesting, this is not something I considered before. Small question as I am not familiar with: do Cloudflare redirects work locally?

Nope, it only works when you hit their servers

**Comment by HiDeoo** [comment]
> > Thanks for your feedback 🙌
> > Interesting, this is not something I considered before. Small question as I am not familiar with: do Cloudflare redirects work locally?
> 
> Nope, it only works when you hit their servers

That's interesting. This makes me wonder if these links should not be external so they work both in prod and dev environments? 🤔 Is the expected experience to get a 404 locally?

**Comment by stavros-k** [comment]
I suppose yes. 
Which is probably why I thought to have the ignore list / func, instead of trying to handle those somehow.
Do you have anything else in mind?

**Comment by HiDeoo** [comment]
My thinking at the moment is that is they were external links, this plugin would automatically ignore them, and they would work both locally and in production (which I think is a better experience because it just works and you can actually see when you make a mistake).

(just to be sure, my questions are not to dismiss the idea, more to understand the exact problem and see if an ignore list is really the better approach as it can open a can of worms)

**Comment by stavros-k** [comment]
I could use full urls like https://example.com/s/discord, which should make validation ignore them, but I like to have them as `/s/discord`, so I dont like to hardcode the domain on a bunch of places.

**Comment by HiDeoo** [comment]
Thanks for the feedback and answering my questions.

[`v0.8.0`](https://github.com/HiDeoo/starlight-links-validator/releases/tag/v0.8.0) now includes an [`exclude`](https://starlight-links-validator.vercel.app/configuration/#exclude) option:

```js
export default defineConfig({
  integrations: [
    starlight({
      plugins: [
        starlightLinksValidator({
          exclude: ['/social/discord', '/social/twitter'],
        }),
      ],
    }),
  ],
})
```

**Comment by stavros-k** [comment]
Awesome!
Thanks
