### ISSUE TITLE
`Exclude` Glob/Wildcard Support

### ISSUE THREAD

**Issue by DuroCodes** [HiDeoo/starlight-links-validator#41]
### Is your feature request related to a problem?

I'm using `starlight-typedoc`, and it generates relative links. It would be nice if it was possible to exclude the entire `/api/` directory so link validation works.

### Describe the solution you'd like

An ideal solution would be a glob-like/wildcard syntax support for the `exclude` option, such as:

```js
starlightLinksValidator({
  exclude: ['/api/*'],
}),
```

Maybe, instead of being in the `exclude` option, since that would exclude all links of the `/api/*` routes, it could be another option to ignore validation within a certain directory?

**Comment by HiDeoo** [comment]
Thanks for the feedback 🙌 

The [`exclude`](https://starlight-links-validator.vercel.app/configuration/#exclude) option now supports [glob patterns](https://github.com/micromatch/picomatch#globbing-features).

> Maybe, instead of being in the `exclude` option, since that would exclude all links of the `/api/*` routes, it could be another option to ignore validation within a certain directory?

That would be up to the user to either choose a pattern that matches everything or restrict it to some specific subdirectories, e.g. `'/api/{interface,functions}/**/*'`.
