### ISSUE TITLE
feat: validate links in the `astro.config.mjs` sidebar directive

### ISSUE THREAD

**Issue by jbergstroem** [HiDeoo/starlight-links-validator#53]
### Is your feature request related to a problem?

When handling the sidebar manually, links can become incorrect as you move content around. Having the link validator handle this would be a great catch before pushing broken sidebar links to production.

### Describe the solution you'd like

The link validator would help find broken sidebar links.

**Comment by HiDeoo** [comment]
Starting with Starlight version [`0.25.0`](https://github.com/withastro/starlight/releases/tag/%40astrojs%2Fstarlight%400.25.0), internal sidebar links can be specified using their `slug` either as a string or an object with a `slug` property:

```js
starlight({
  title: 'My Docs',
  sidebar: ['getting-started', { slug: 'guides/installation' }],
});
```

When using this approach, on top of being easier to write, Starlight will error out if a specified `slug` does not exist:

<img width="1214" alt="image" src="https://github.com/user-attachments/assets/838e4df3-1004-4dff-a470-90d196faf570">

Considering this validation exists in Starlight, I don't think adding a similar feature to the plugin would be beneficial.
