### ISSUE TITLE
Starlight links validator 'Getting Started' site is down

### ISSUE THREAD

**Issue by jfrome1** [HiDeoo/starlight-links-validator#54]
### Describe the bug

The site `https://starlight-links-validator.vercel.app/` gives error 'deployment not found'.

### To Reproduce

Go to site

### Expected behavior

Site loads

### How often does this bug happen?

Every time

**Comment by HiDeoo** [comment]
Thanks for your report.

I tried to repro locally, in an incognito window, and in different browsers, but I couldn't. I also tried this [3rd-party service](https://www.site-shot.com/) which takes a screenshot of a website and I got the expected result.

<img width="1125" alt="image" src="https://github.com/user-attachments/assets/5ff2f687-9409-4259-bb27-7b5309ecf8d6">

Maybe it was a temporary issue on Vercel's side, not sure.
