### ISSUE TITLE
New configuration option to ignore anchor links?

### ISSUE THREAD

**Issue by kodster28** [HiDeoo/starlight-links-validator#57]
### Is your feature request related to a problem?

Hey hey, love all the stuff you've built (we're just getting used to it on [developers.cloudflare.com](https://developers.cloudflare.com)).

As part of our previous build workflow (in Hugo), we had the following split between evaluating internal links:

- Every commit -> Broken internal links (and check for build + infinite redirects). This check was required.
- Every weekend -> Maintenance check for broken anchor links.

Essentially, it just wasn't worth it to fail the build for anchor links b/c we have a metric ton of content + we didn't want to inconvenience contributors.

### Describe the solution you'd like

Would it be possible to add a new [configuration option](https://starlight-links-validator.vercel.app/configuration/) where the link checker ignores the anchor part of links?

I'd love to be able to tap into the logic you've already built... but be able to tailor it a bit more specifically.

### Describe alternatives you've considered

I've thought about writing something from scratch, but it seems like this is very close to our use case.

**Comment by jarodtaylor** [comment]
I'm running into issues with this, as well. All of our internal anchor links (e.g. #another-section-of-page) fails the validator showing `invalid anchor`.

**Comment by HiDeoo** [comment]
Thanks for the feedback :raised_hands:

This is definitely a scenario/workflow that I didn't consider at all. Adding something like `errorOnInvalidAnchors` or something similar would definitely be possible to accommodate this use case. This would obviously be an option enabled by default.

I'd like to take a bit more time to think about it/make sure there aren't any other edge cases that I'm not considering before jumping into it but I'm definitely not opposed to the idea.

**Comment by kodster28** [comment]
Thanks, @HiDeoo!

**Comment by HiDeoo** [comment]
No problem, thanks for the great feedback.

The new [`errorOnInvalidHashes`](https://starlight-links-validator.vercel.app/configuration/#erroroninvalidhashes) option should now be available in the [`v0.12.0`](https://github.com/HiDeoo/starlight-links-validator/releases/tag/v0.12.0) release that I just published.
