### ISSUE TITLE
Ignore links in draft posts

### ISSUE THREAD

**Issue by iwoplaza** [HiDeoo/starlight-links-validator#65]
### Describe the bug

Links in draft .mdx files are includes in the validation process. It would be awesome if every file marked `draft: true` in its frontmatter was ignored in validation 🙏.

### To Reproduce

1. Create an .mdx file marked as "draft: true".
2. Create a link to another draft file.
3. The validation process fails.

### Expected behavior

Links in draft files are ignored.

### How often does this bug happen?

Every time

**Comment by HiDeoo** [comment]
Thanks for the report, definitely something I didn't think about :raised_hands:

This should now be fixed in the version [`0.12.4`](https://github.com/HiDeoo/starlight-links-validator/releases/tag/v0.12.4) that I just published.
