### ISSUE TITLE
Don't error on links pointing to a fallback page

### ISSUE THREAD

**Issue by lorenzolewis** [HiDeoo/starlight-links-validator#9]
### Describe the bug

Currently when linking to a page that doesn't exist on disk but will be generated as a fallback page an error will prevent build.

### To Reproduce

1. Have a pages `src/content/docs/foo.mdx`, `src/content/docs/bar.mdx` and `src/content/docs/fr/foo.mdx`
2. In `src/content/docs/fr/foo.mdx` link to `/fr/bar`
3. Build and see error

### Expected behavior

Even though `src/content/docs/fr/bar.mdx` doesn't exist on disk, it will still be generated during build with a valid Astro config and will be a valid link. This should not error (or at the very least could warn but not error).

### How often does this bug happen?

Every time

### System Info

"@astrojs/starlight": "^0.9.0"
"astro": "^3.0.7"
"starlight-links-validator": "^0.3.0"

### Additional Context

Additionally we spoke on Discord about different ways to treat errors based on a glob pattern. i.e. for files in `src/content/docs/fr/[...slug]` only warn, but for everything else error.

Thanks for the awesome "integration"!

**Comment by HiDeoo** [comment]
Adding a little bit of context for people seeing this issue:

- This is something planned but I did not have the time to come back to it yet.
- There will be an option or a "mode" to switch between the current behavior and the proposed one as after some discussions, it seems that some people do want an error if they *explicitly* link to a translated page that should exist but does not yet.

**Comment by HiDeoo** [comment]
This took a bit of time but this is now supported in [`v0.5.0`](https://github.com/HiDeoo/starlight-links-validator/releases/tag/v0.5.0) by setting the new `errorOnFallbackPages` option to `false`:

```js
export default defineConfig({
  integrations: [
    starlight({
      plugins: [
        starlightLinksValidator({
          errorOnFallbackPages: false,
        }),
      ],
    }),
  ],
})
```

Thanks for your patience.
